.PHONY: clients
.DEFAULT_GOAL := clients
# Re-create autogenerated client code from OpenAPI spec
clients:
	kiota generate -l python -d http://moma-management:5000/openapi.json -o ap_management/generated/moma_management -c MomaManagementClient